language: php
cache:
  directories:
    - node_modules
php:
  - '7.1'
  - '7.0'
  - '5.6'
before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g yarn
  - yarn install
install:
  - composer install
  - php artisan key:generate
  - gulp
script:
  - ./vendor/bin/phpunit
notifications:
  email:
    on_success: never
    on_failure: never