language: php
cache:
  directories:
    - node_modules
php:
  - '7.1'
  - '7.0'
  - '5.6'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - yarn install
install:
  - composer install
  - php artisan key:generate
  - gulp
script:
  - ./vendor/bin/phpunit
notifications:
  email:
    on_success: never
    on_failure: never